### ISSUE TITLE
microbe catalogue starter

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/data-catalogue-microbe#2]
- [x] [repo](https://github.com/ebi-ait/data-catalogue-microbe) for microbe
- [x] react-admin basic project
- [x] connection to biosamples
- [x] show a few fields
- [x] deploy to dev on k8s
  - [x] helm chart
  - [ ] fix problem with "image pull secret"
- [ ] connect to wwwdev
- [ ] paging
- [ ] colours, fonts
- [ ] filtering

**Comment by ESapenaVentura** [comment]
@amnonkhen I have started a very simple miro board with all the fields I would like to see, both for filtering and display:

https://miro.com/app/board/uXjVLWm0FF8=/?share_link_id=579650007877

Let me know if it's not clear!
